title: "Period Doubling and a Route to Chaos"
description: "Exploring nonlinear dynamics, period doubling, and chaos through simulation in UDK and Octave."
url: "https://oospakooysa.github.io"
baseurl: "/period_doubling"

theme: minima

author:
  name: oospakooysa
  email: 234571357+oospakooysa@users.noreply.github.com

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
