title: "Period Doubling and a Route to Chaos"
description: "Exploring nonlinear dynamics, period doubling, and chaos through simulation in UDK and Octave."
url: "https://oospakooysa.github.io"
baseurl: "/period_doubling"

remote_theme: "jekyll/minima"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
